// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/BookADemo.tsx";
import * as $$$$$$2 from "./sections/Buttons.tsx";
import * as $$$$$$3 from "./sections/DetailedHero.tsx";
import * as $$$$$$4 from "./sections/Faq.tsx";
import * as $$$$$$5 from "./sections/Features.tsx";
import * as $$$$$$6 from "./sections/Footer.tsx";
import * as $$$$$$7 from "./sections/Header.tsx";
import * as $$$$$$25 from "./sections/hero-1.tsx";
import * as $$$$$$26 from "./sections/hero-2.tsx";
import * as $$$$$$8 from "./sections/Hero.tsx";
import * as $$$$$$27 from "./sections/hero2.tsx";
import * as $$$$$$9 from "./sections/Hero3.tsx";
import * as $$$$$$10 from "./sections/HtmxHeader.tsx";
import * as $$$$$$11 from "./sections/ImageSelector.tsx";
import * as $$$$$$12 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$13 from "./sections/ItemsSearcher.tsx";
import * as $$$$$$14 from "./sections/Logos.tsx";
import * as $$$$$$15 from "./sections/Plans.tsx";
import * as $$$$$$16 from "./sections/PostContent.tsx";
import * as $$$$$$17 from "./sections/PostTop.tsx";
import * as $$$$$$18 from "./sections/SimpleHero.tsx";
import * as $$$$$$19 from "./sections/SmallImageHero.tsx";
import * as $$$$$$20 from "./sections/StatisticsHero.tsx";
import * as $$$$$$21 from "./sections/StoriesHero.tsx";
import * as $$$$$$22 from "./sections/Testimonials.tsx";
import * as $$$$$$23 from "./sections/Theme/Theme.tsx";
import * as $$$$$$24 from "./sections/Video.tsx";

const manifest = {
  "sections": {
    "site/sections/BlogPosts.tsx": $$$$$$0,
    "site/sections/BookADemo.tsx": $$$$$$1,
    "site/sections/Buttons.tsx": $$$$$$2,
    "site/sections/DetailedHero.tsx": $$$$$$3,
    "site/sections/Faq.tsx": $$$$$$4,
    "site/sections/Features.tsx": $$$$$$5,
    "site/sections/Footer.tsx": $$$$$$6,
    "site/sections/Header.tsx": $$$$$$7,
    "site/sections/hero-1.tsx": $$$$$$25,
    "site/sections/hero-2.tsx": $$$$$$26,
    "site/sections/Hero.tsx": $$$$$$8,
    "site/sections/hero2.tsx": $$$$$$27,
    "site/sections/Hero3.tsx": $$$$$$9,
    "site/sections/HtmxHeader.tsx": $$$$$$10,
    "site/sections/ImageSelector.tsx": $$$$$$11,
    "site/sections/ImageWithParagraph.tsx": $$$$$$12,
    "site/sections/ItemsSearcher.tsx": $$$$$$13,
    "site/sections/Logos.tsx": $$$$$$14,
    "site/sections/Plans.tsx": $$$$$$15,
    "site/sections/PostContent.tsx": $$$$$$16,
    "site/sections/PostTop.tsx": $$$$$$17,
    "site/sections/SimpleHero.tsx": $$$$$$18,
    "site/sections/SmallImageHero.tsx": $$$$$$19,
    "site/sections/StatisticsHero.tsx": $$$$$$20,
    "site/sections/StoriesHero.tsx": $$$$$$21,
    "site/sections/Testimonials.tsx": $$$$$$22,
    "site/sections/Theme/Theme.tsx": $$$$$$23,
    "site/sections/Video.tsx": $$$$$$24,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
